
export const ORDER_SUM: 'ORDER_SUM' = 'ORDER_SUM';
export const GET_NUMBER: 'GET_NUMBER' = "GET_NUMBER";
export const GET_NUMBER_SUCCES: 'GET_NUMBER_SUCCES' = "GET_NUMBER_SUCCES";
export const GET_NUMBER_FAILED: 'GET_NUMBER_FAILED' = "GET_NUMBER_FAILED";
export const NUMBER_REMOVE: 'NUMBER_REMOVE' = "NUMBER_REMOVE";
export const TOGGLE_ITEM_CONSTRUCTOR: 'TOGGLE_ITEM_CONSTRUCTOR' = "TOGGLE_ITEM_CONSTRUCTOR";
export const ADD_ITEM_CONSTRUCTOR: 'ADD_ITEM_CONSTRUCTOR' = "ADD_ITEM_CONSTRUCTOR";
export const ADD_BUN_CONSTRUCTOR: 'ADD_BUN_CONSTRUCTOR' = "ADD_BUN_CONSTRUCTOR";
export const DELETE_ITEM_CONSTRUCTOR: 'DELETE_ITEM_CONSTRUCTOR' = "DELETE_ITEM_CONSTRUCTOR";
