
export const VISIBLE_LIST = "VISIBLE_LIST";
export const DISABLED_LIST = "DISABLED_LIST";
export const DISABLED_MODAL = "DISABLED_MODAL";
export const VISIBLE_MODAL = "VISIBLE_MODAL";
export const TOGGLE_VISIBLE = "TOGGLE_VISIBLE";
export const TOGGLE_VISIBLE_LIST = "TOGGLE_VISIBLE_LIST";
export const OPEN_POPUP_INGREDIENTS = "OPEN_POPUP_INGREDIENTS";
export const OPEN_POPUP_ORDER = "OPEN_POPUP_ORDER";
export const CLOSE_POPUP_ORDER = "CLOSE_POPUP_ORDER";
export const OPEN_POPUP_ORDER_INGREDIENTS = "OPEN_POPUP_ORDER_INGREDIENTS";



