
export const TOGGLE_VISIBLE = "TOGGLE_VISIBLE";
export const OPEN_POPUP_INGREDIENTS = "OPEN_POPUP_INGREDIENTS";
export const OPEN_POPUP_ORDER = "OPEN_POPUP_ORDER";
export const CLOSE_POPUP_ORDER = "CLOSE_POPUP_ORDER";
export const OPEN_POPUP_ORDER_INGREDIENTS = "OPEN_POPUP_ORDER_INGREDIENTS";



