export const AUTH_LOGIN: 'AUTH_LOGIN' = 'AUTH_LOGIN';
export const AUTH_REGISTER: 'AUTH_REGISTER' = "AUTH_REGISTER";
export const AUTH_LOGOUT: 'AUTH_LOGOUT' = "AUTH_LOGOUT";
export const AUTH_TOKEN: 'AUTH_TOKEN' = "AUTH_TOKEN";
export const AUTH_FAILED: 'AUTH_FAILED' = "AUTH_FAILED";
export const AUTH_SUCCESS: 'AUTH_SUCCESS' = "AUTH_SUCCESS";
export const GET_USER: 'GET_USER' = "GET_USER";
